cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

# Docker (commented out, using Docker for Mac now)
# brew 'docker'
# brew 'docker-machine'
# brew 'docker-compose'

# Utils
brew 'zsh'
brew 'openssl'
brew 'nmap'
brew 'wget'
brew 'coreutils'
brew 'findutils'
brew 'readline'
brew 'autojump'
brew 'jq'
brew 'ngrep'
brew 'ack'
brew 'gnu-sed'
brew 'fzf'
brew 'fpp'
brew 'hub'
brew 'ffmpeg'
brew 'peco'
brew 'the_silver_searcher'

# Dev
cask 'java' unless system '/usr/libexec/java_home --failfast'
brew 'git'
brew 'git-extras'
brew 'mercurial'
brew 'node'
brew 'leiningen'
brew 'ant'
brew 'maven'
brew 'sbt'
brew 'python'
brew 'python3'
brew 'pyenv'
brew 'pyenv-virtualenvwrapper'
brew 'node'
brew 'redis'
brew 'go', args: ['cross-compile-common']

# GUI
cask '1password'
cask 'alfred'
cask 'dropbox'
cask 'dropshare'
cask 'evernote'
cask 'google-chrome'
cask 'iterm2-beta'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'virtualbox'
cask 'vlc'
