echo "Installing Homebrew packages and casks..."

cat <<EOF | brew bundle --file=/dev/stdin
cask_args appdir: '/Applications'

tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'yqrashawn/goku'

# Utils
brew 'zsh'
brew 'openssl'
brew 'nmap'
brew 'wget'
brew 'coreutils'
brew 'findutils'
brew 'readline'
brew 'autojump'
brew 'jq'
brew 'ngrep'
brew 'ack'
brew 'gnu-sed'
brew 'fzf'
brew 'fpp'
brew 'hub'
brew 'ffmpeg'
brew 'peco'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'chezmoi'
brew 'pipx'
brew 'mas'
brew 'goku'

# Dev
cask 'temurin'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'git-filter-repo'
brew 'mercurial'
brew 'node@16'
brew 'leiningen'
brew 'ant'
brew 'maven'
brew 'sbt'
brew 'python'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'redis'
brew 'go'
brew 'direnv'
brew 'awscli'
brew 'starship'

# GUI
cask '1password'
cask 'alfred'
cask 'bartender'
cask 'bitbar'
cask 'docker'
cask 'dropbox'
cask 'dropshare'
cask 'notion'
cask 'font-fira-mono-nerd-font'
cask 'google-chrome'
cask 'iina'
cask 'iterm2-beta'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'telegram-desktop'
cask 'vlc'
cask 'vscodium'
EOF
