add_newline = true
command_timeout = 1000

[character]
success_symbol = "[λ](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncate_to_repo = false
repo_root_style = "bold blue"
truncation_length = 8
truncation_symbol = "…/"

[python]
format = 'via [${symbol}${pyenv_prefix}(${virtualenv} )(\($version\) )]($style)'

[package]
disabled = true

[git_metrics]
disabled = false

[git_branch]
symbol = " "
